### ISSUE TITLE
[Request deployment] New Hub: {{ HUB NAME }}

### ISSUE THREAD

**Issue by GeorgianaElena** [GeorgianaElena/.github#51]
### Hub Authentication Type

pending

### [GitHub Auth only] How would you like to manage your users?

None

### Extra features you'd like to enable

- [ ] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state
