### ISSUE TITLE
[EVENT] {{ HUB NAME }}

### ISSUE THREAD

**Issue by GeorgianaElena** [GeorgianaElena/.github#65]
### The link towards the Freshdesk ticket this event was reported

kjhk

### The date when the event will start

kh

### The date when the event will end

jlk

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

okjlk

### Are we three weeks before the start date of the event?

- [ ] Yes
- [ ] No

### Number of attendees

65

### Make sure to add the event into the calendar

- [ ] Done

### Does the hub already exist?

- [ ] Yes
- [ ] No

### The URL of the hub that will be used for the event

lkml

### Will this hub be decommissioned after the event is over?

- [ ] Yes
- [ ] No

### Task list

```[tasklist]
- [ ] Was all the info filled in above?
- [ ] Quotas from the cloud provider are high-enough to handle expected usage?
```

### Definition of Done

```[tasklist]
- [ ] All the tasks have been completed
```
